.gitignore, .nvmrc, README.md, package-lock.json, package.json
Added some infos to help folks get running
=> Getting started

.env.default, README.md, docker-compose.yml, package-lock.json, package.json
* Removes the need to have a local mongodb install under development.
* Allows a more efficient and consistent onboarding + dev experience.
* Adds a mongo db admin ui for free.
=> use docker-compose for mongodb

package.json
Oopsie, sorry...
* fixes commands running sequentially (should run in parallel)
=> fix "npm run dev" not starting the app

ui/components/Gallery.js, ui/pages/[dream]/index.js
* adds a generic, reusable _Gallery_ component
* uses this Gallery component on the Dreams page to show all images of a Dream
* uses a responsive modal (adapts to height / width of the viewport)
* Renders the Gallery component only if the number of images for a dream >= 2.
=> 17 display images

api/database/models.js, api/resolvers/index.js, api/schema/index.js, ui/components/DreamCard.js, ui/components/EditOrCreateDreamForm.js, ui/pages/[dream]/index.js, ui/pages/index.js
- Add summary field on edit & create dream
- Update schema & resolver
- Display summary on DreamCard and on Dream Page
=> 18 summary field

api/database/models.js, api/resolvers/index.js, api/schema/index.js, now.json, ui/components/EditBudgetItems.js, ui/components/EditOrCreateDreamForm.js, ui/components/ImageUpload.js, ui/components/admin-page/EditEventForm.js, ui/pages/[dream]/index.js
=> Add budget items

.env.default
Added missing envs
* `PRETIX_URL`
* `PRETIX_TOKEN`
=> Added missing default env variables

api/database/models.js, api/resolvers/index.js, api/schema/index.js, ui/components/Comment.js, ui/components/EditComment.js
Added ability to edit existing comments.
- Added updatedAt to Comment
- Added a validation that user has access to that comment
- Added a new edit comment component
- Only displayed when user can edit the comment (Original Author)
- Tested users without permissions - displayed an error message of "Cant find that comment - Does this comment belongs to you?"
- Tested edit comments. Then deleting them
- Tested showing comments without ability to edit
Notice the top part doesn't have the "Edit" icon
UI on edit:
=> Edit existing comments

api/database/models.js, api/resolvers/index.js, api/schema/index.js, ui/components/Modal/EditProfile.js, ui/components/Modal/FinishSignUp.js, ui/components/members/MembersTable.js, ui/components/members/index.js, ui/pages/_app.js, ui/pages/profile.js
* User bio on the UI and on the models level
* Added bio to the members area to allow admin to see the different skills each user has
User bio is a multiline (4 rows) field on the ui
* Tested that members is working without any bio
* Updating a bio for a user
* Created a long bio text - members area still looks good. Edit profile doesn't break.
=> Added user bio

api/database/models.js, api/schema/index.js, api/utils/calculateGoals.js, ui/components/Dream/Budget.js, ui/components/Dream/EditBudgetModal.js, ui/components/Dream/index.js, ui/pages/[event]/[dream]/index.js
Breaking changes:
- budget items in database need a type field of either `INCOME` or `EXPENSE`
=> Allow adding Income budget items

ui/components/Granting/SetCurrency.js, ui/pages/create-event.js
=> Added new currency nok

README.md, api/resolvers/index.js, api/schema/index.js, ui/components/EventSettingsModal/DraggableCustomFields.js
Small refactoring of custom fields ordring
=> Made custom fields simpler

ui/components/Dream/EditBudgetModal.js, ui/components/EventSettingsModal/AddOrEditCustomField.js, ui/components/Header.js, ui/package-lock.json, ui/package.json
Fixes a bug reported on the [Blivande forum](https://forum.blivande.com/t/testing-blivande-dreams/1078/26?u=gustav).
React hook form has a special hook to deal with dynamic array forms, **useFieldArray**, which we were not using and was causing some weird bugs. Using the correct hook solved everything 😃
=> Fix edit budget form

ui/components/EventSettingsModal/GeneralSettings.js
Hot fix to allow users to update event details
=> Fixes #100 - Form now identifies dirty and allow to update it

ui/components/EventSettingsModal/AddOrEditCustomField.js
=> Fixed an issue where show on front page and is required didnt worked

ui/lib/auth.js, ui/package-lock.json, ui/package.json, ui/pages/api/callback.js, ui/pages/api/login.js
Fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/160
=> Switch auth redirect from being stored in query string to cookies

ui/.env.development, ui/.env.production, ui/components/Organizations/EditOrganization.js, ui/components/TextField.js, ui/next.config.js, ui/pages/api/login.js, ui/pages/organizations/[organization]/edit.js, ui/pages/organizations/create.js, ui/pages/organizations/index.js
to test go to `http://localhost:3000/organizations/create?from=realities` (realities will send users to this url)
=> Allow a Realities user to use the Create organization screen

.nvmrc
Updated to latest stable node version as Gustav already using that one but this file was yet to be updated.
Fixes issues with unknown ?? and ?. operators
=> Updated to latest stable node version in .nvmrc to 14.x aka Fermium

api/resolvers/index.js
Fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/198
=> Don't break when an org doesn't have discourse

api/resolvers/index.js
Fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/170
Manually tested once
=> Don't let people put special characters in their org slugs

api/database/models/event.js, api/resolvers/index.js, ui/components/Avatar.js, ui/components/EventSettingsModal/CustomFields/DraggableCustomFields.js, ui/components/EventSettingsModal/CustomFields/index.js, ui/components/EventSettingsModal/DraggableItems.js, ui/components/EventSettingsModal/Guidelines/DraggableGuidelines.js, ui/components/EventSettingsModal/Guidelines/index.js, ui/components/TextField.js, ui/pages/_document.js
Fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/120
Bug described in the issue
=> Fix reordering bug for guidelines and custom fields

ui/.env.development, ui/.env.production, ui/components/Dream/Comments/index.js, ui/lib/apollo.js, ui/lib/realities/createRealitiesApollo.js, ui/lib/realities/queries.js, ui/lib/realities/subscriptions.js, ui/next.config.js, ui/package-lock.json, ui/pages/[event]/about.js, ui/pages/realities/index.js
Fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/195
Technically works now but should be cleaned up. And e.g. doesn't have ssr for now
=> Set up ability to access the realities api from dreams through apollo

ui/components/Layout.js
Fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/208
=> Add footer with gdpr links

api/controller/index.js, api/resolvers/index.js, api/schema/index.js, ui/components/Switch.js, ui/components/members/AllocateModal.js, ui/components/members/BulkAllocateModal.js, ui/components/members/MembersTable.js, ui/components/members/index.js
Adds ability on the event members page to bulk allocate funds to members, both adding and setting. Also adds the Set option for individual allocations.
=> Bulk allocation of funds and ability to set (instead of add) balances

api/index.js, api/package-lock.json, api/package.json, api/scripts/requireAcceptToS.js, api/utils/initKcAdminClient.js
fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/207
This PR doesn't actually do the change itself, but it adds the script that i used to do the change. We'll be able to use it (a slight modification of it) if we need to ask users in the future to accept the ToS again.
This was just for already existing users. The normal setting in keycloak will make sure new users need to accept the ToS
=> Require the user to accept the ToS and privacy policy

ui/components/Layout.js, ui/pages/privacy-policy.js, ui/pages/terms-and-conditions.js
Due to https://github.com/Edgeryders-Participio/plato-core/issues/7#issuecomment-852058636
=> Use redirects to sent people to the terms and conditions and privacy policy

ui/pages/privacy-policy.js, ui/pages/terms-and-conditions.js
Contributes to https://github.com/Edgeryders-Participio/plato-core/issues/7 since google seems very bothered by us having our policies on someone else's website
=> Move the Privacy Policy, and Terms and Condition to iframes

ui/lib/apolloClient.js
Fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/279
=> Fix cache bug on dreams filtering

api/resolvers/index.js
Fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/278
=> Randomize order of dreams list

api/resolvers/index.js
Reverts Edgeryders-Participio/multi-dreams#289
=> Revert "Randomize order of dreams list, take 2"

api/resolvers/index.js
prev https://github.com/Edgeryders-Participio/multi-dreams/pull/289
Image ids got broken by the mongo aggregation
=> Randomize order of dreams list, take 3

api/resolvers/index.js
Reverts Edgeryders-Participio/multi-dreams#292
=> Revert "Randomize order of dreams list, take 3"

api/resolvers/index.js
prev https://github.com/Edgeryders-Participio/multi-dreams/pull/292
fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/278
fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/32
fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/293
=> Randomize order of dreams list, take 4

ui/components/Dream/ContributeModal.js
Resolves https://github.com/Edgeryders-Participio/multi-dreams/issues/299
Seems almost too simple, but haven't run into any issues in my (not very elaborate tbh) testing
=> Allow contributing cents

api/package-lock.json, api/package.json
Hoping this helps with https://github.com/Edgeryders-Participio/multi-dreams/pull/241
=> Update apollo server to 2.25.2

api/lib/discourse.js
Fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/210
=> Load entire comment threads from discourse

ui/components/Dream/CustomFields/DreamCustomField.js
dream where you can verify the behaviour (prod db) http://dev-org.localhost:3000/my-event/613f3d53f54cf1cf7577502f
=> Wrap lines in md code blocks if too long

.eslintignore
Workaround for https://github.com/Edgeryders-Participio/multi-dreams/issues/334
=> Ignore eventhub file in eslint

ui/components/EventSettings/index.js, ui/components/Header/OrganizationAndEventHeader.js, ui/components/Header/index.js, ui/components/SubMenu.js
Fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/243
=> Fix small mobile ui bugs

api/subscribers/discourse.subscriber.js, ui/components/Dream/Budget.js, ui/components/Dream/EditBudgetModal.js
Fixes https://github.com/Edgeryders-Participio/multi-dreams/issues/340 and a bit more
=> Update budget ux/copy

LICENSE, README.md
fixes https://github.com/cobudget/cobudget/issues/444
=> Switch to new license based on the pretix license

ui/components/Bucket/Overview.tsx, ui/components/Bucket/Sidebar.tsx, ui/components/Monster.js, ui/pages/[org]/[collection]/[bucket]/index.tsx
This PR fixes https://github.com/cobudget/cobudget/issues/373
=> style: review prompt made responsive

ui/components/EventMembers/index.tsx, ui/components/Wysiwyg.tsx, ui/server/graphql/resolvers/index.ts, ui/server/graphql/schema/index.js
does https://github.com/cobudget/cobudget/issues/554
and partially/fully? https://github.com/cobudget/cobudget/issues/555
=> Change round member and mention search to be case insensitive, and search for names as well

ui/components/AuthenticationForm.tsx, ui/pages/api/auth/logout.ts, ui/server/api-handler.ts
for https://github.com/cobudget/cobudget/issues/495
=> Add checkbox to opt into staying signed in

ui/components/Bucket/Sidebar.tsx
for https://github.com/cobudget/cobudget/issues/358
=> Make canceling bucket scarier

ui/pages/[org]/[collection]/[bucket]/index.tsx, ui/server/graphql/resolvers/helpers.ts, ui/server/graphql/resolvers/index.ts
for https://github.com/cobudget/cobudget/issues/515
=> Just show blank page when visiting bucket in hidden round

ui/components/UserSettings/index.tsx
for https://github.com/cobudget/cobudget/issues/491
=> Email settings copy and order update

ui/pages/[org]/[collection]/index.tsx, ui/pages/_app.tsx, ui/server/graphql/resolvers/index.ts, ui/server/graphql/schema/index.js
for https://github.com/cobudget/cobudget/issues/366
=> Change display of available funds

ui/components/Group/EditGroup.js
fixes https://github.com/cobudget/cobudget/issues/635
=> fix: cloudinary preset for groups

ui/components/Header/index.tsx
for https://github.com/cobudget/cobudget/issues/639
=> join round button color

ui/pages/_app.tsx
for https://github.com/cobudget/cobudget/issues/629
=> fix: fetch tags in query

ui/components/Group/GroupMembers/GroupMembersTable.tsx, ui/components/Group/GroupMembers/index.tsx, ui/graphql/client.ts, ui/server/graphql/resolvers/index.ts, ui/server/graphql/schema/index.js
for https://github.com/cobudget/cobudget/issues/655
=> Fix error on deleting rounds

ui/pages/[group]/[round]/[bucket]/index.tsx
for https://github.com/cobudget/cobudget/issues/521
=> Bucket page slugs

ui/server/graphql/resolvers/index.ts, ui/server/services/EmailService/email.service.ts
for https://github.com/cobudget/cobudget/issues/637
=> feat: send email on member request

ui/components/Header/index.tsx
for https://github.com/cobudget/cobudget/issues/630
=> fix: fetch registration policy

ui/pages/api/connect-discourse.ts, ui/pages/api/index.ts, ui/server/graphql/resolvers/index.ts, ui/server/lib/discourse.tsx, ui/server/subscribers/discourse.subscriber.ts, ui/utils/createDiscourseConnectUrl.js
Needs testing with a Discourse server
=> Fix discourse integration

ui/components/Bucket/Funders.tsx
for https://github.com/cobudget/cobudget/issues/665
=> fix: use colon

ui/components/Bucket/ContributeModal/index.tsx, ui/components/Bucket/Overview.tsx, ui/components/Bucket/Sidebar.tsx, ui/components/Group/EditGroup.js, ui/components/RoundSettings/Granting/index.tsx, ui/pages/[group]/[round]/[bucket]/index.tsx, ui/pages/_app.tsx, ui/server/graphql/schema/index.js, ui/server/prisma/migrations/20220607140636_experimental_features_flag_on_groups/migration.sql, ui/server/prisma/schema.prisma
For https://github.com/cobudget/cobudget/issues/731
Merging into https://github.com/cobudget/cobudget/pull/699
=> Experimental features flag on groups

ui/server/controller/index.ts, ui/server/graphql/resolvers/index.ts, ui/server/send-email.ts, ui/server/services/EmailService/email.service.ts, ui/server/subscribers/email.subscriber.ts
Fix for #756.
Instead of doing `n * k` db queries when bulk allocating we are simply doing `k`
=> Bulk allocate optimization

ui/server/controller/index.ts, ui/server/graphql/resolvers/index.ts, ui/server/send-email.ts, ui/server/services/EmailService/email.service.ts, ui/server/subscribers/email.subscriber.ts
* Bulk allocate optimization
* Prettify template literal
* Use correct var
* send emails in batches
* yarn fix
=> Bulk allocate optimization (#759)

ui/components/Bucket/Sidebar.tsx
for https://github.com/cobudget/cobudget/issues/751
=> hide review for admins if reviews are off

ui/components/Bucket/Sidebar.tsx
for https://github.com/cobudget/cobudget/issues/371
=> show bucket status on bucket page

ui/components/Bucket/Budget.tsx, ui/components/RoundSettings/DeleteRoundModal.js
for https://github.com/cobudget/cobudget/issues/734
=> fix: formatted number

ui/components/Filterbar/StatusFilter.tsx
for https://github.com/cobudget/cobudget/issues/726
=> fix: status filter

ui/pages/[group]/[round]/[bucket]/index.tsx, ui/server/graphql/schema/index.js
fixes https://github.com/cobudget/cobudget/issues/793
=> fix: fetch createdAt

ui/components/Filterbar/index.js
for https://github.com/cobudget/cobudget/issues/792
=> dont scroll on status change

ui/components/Group/GroupMembers/GroupMembersTable.tsx, ui/components/Group/GroupMembers/RequestToJoinGroup.tsx, ui/components/Group/GroupMembers/index.tsx, ui/components/Group/NewGroup/index.tsx, ui/components/Group/Settings/GeneralSettings.tsx, ui/components/Group/index.tsx, ui/components/Header/index.tsx, ui/components/RoundMembers/RequestToJoinTable.tsx, ui/graphql/client.ts, ui/pages/[group]/[round]/index.tsx, ui/pages/_app.tsx, ui/pages/api/stripe/create-checkout-session.ts, ui/server/controller/index.ts, ui/server/graphql/resolvers/helpers.ts, ui/server/graphql/resolvers/index.ts, ui/server/graphql/schema/index.js, ui/server/prisma/migrations/20220718061438_group_registration_policy/migration.sql, ui/server/prisma/migrations/20220724180941_group_member_fields/migration.sql, ui/server/prisma/migrations/20220725060403_group_visibility/migration.sql, ui/server/prisma/schema.prisma
for https://github.com/cobudget/cobudget/issues/784
Inviting group members don't work. It is another issue.
=> Hidden groups

ui/components/Header/Selector.tsx
for https://github.com/cobudget/cobudget/issues/713
=> fix: override webflow styles

ui/components/Header/Selector.tsx, ui/server/controller/index.ts
for https://github.com/cobudget/cobudget/issues/820
=> make group name, slug public

ui/server/graphql/resolvers/types/Round.ts
fixes unpublished bucket not showing up on round page
=> fix: bucket count

ui/components/Bucket/GrantingStatus.tsx
=> style: line break

ui/components/InviteMembersModal.tsx, ui/pages/invite/[token].tsx, ui/server/graphql/resolvers/types/Round.ts
=> style: change button positions

ui/components/Filterbar/StatusFilter.tsx, ui/pages/[group]/[round]/index.tsx
I haven't linted the code. I think it may result in conflicts.
=> always show all statuses

ui/pages/[group]/[round]/index.tsx
for https://github.com/cobudget/cobudget/issues/841
=> Hide approvals and flags columns when bucket review is disabled

ui/server/graphql/resolvers/mutations/round.ts
for https://github.com/cobudget/cobudget/issues/860
=> fix: bulk allocate

ui/pages/[group]/[round]/index.tsx
for https://github.com/cobudget/cobudget/issues/855
=> fix: show 0 if no goal set

ui/server/graphql/resolvers/queries/round.ts
for https://github.com/cobudget/cobudget/issues/852
=> fix: show rounds to superadmin

ui/components/RoundSettings/Guidelines/DraggableGuidelines.tsx
for https://github.com/cobudget/cobudget/issues/879
=> fix: tooltip

ui/components/Filterbar/index.js
for https://github.com/cobudget/cobudget/issues/837
=> table view for non-admins

ui/server/send-email.ts, ui/server/services/EmailService/email.service.ts
for https://github.com/cobudget/cobudget/issues/754
=> Verified only mails

ui/components/Bucket/CustomFields/BucketCustomField.tsx
for https://github.com/cobudget/cobudget/issues/880
=> fix: translation

ui/server/services/EmailService/email.service.ts, yarn.lock
for https://github.com/cobudget/cobudget/issues/754#issuecomment-1316568703
=> non-verified invitations

ui/components/About/index.tsx, ui/components/BillBreakdown.tsx, ui/components/Bucket/Funders.tsx, ui/components/FormattedCurrency.tsx, ui/components/ProfileDropdown.js, ui/components/RoundMembers/AllocateModal.tsx, ui/components/RoundSettings/Granting/index.tsx, ui/components/Transactions/index.tsx
for https://github.com/cobudget/cobudget/issues/849
=> fix: currency formatting

ui/components/Bucket/EditCocreatorsModal.tsx, ui/server/graphql/resolvers/mutations/bucket.ts
Only members who have joined the round can become the co-creators of the buckets inside the round.
=> Allow only joined members to be cocreators

ui/server/graphql/resolvers/helpers.ts
fixes https://github.com/cobudget/cobudget/issues/898
=> fix: filter cancel buckets

ui/components/Bucket/EditCocreatorsModal.tsx, ui/lang/index.ts, ui/pages/[group]/[round]/index.tsx, ui/server/graphql/resolvers/mutations/bucket.ts
for https://github.com/cobudget/cobudget/issues/849#issuecomment-1323998417
=> format currency

ui/components/Bucket/EditBudgetModal.tsx, ui/components/Bucket/EditCocreatorsModal.tsx, ui/lang/index.ts, ui/server/graphql/resolvers/mutations/bucket.ts
for https://github.com/cobudget/cobudget/issues/840
=> Optional max amount

ui/components/BucketCard.js, ui/pages/[group]/[round]/index.tsx
for https://github.com/cobudget/cobudget/issues/848
=> fix: floor percentage

ui/components/About/index.tsx, ui/components/RoundSettings/BucketReview/index.js, ui/components/RoundSettings/Granting/SetAllowStretchGoals.js, ui/components/RoundSettings/Granting/SetRequireBucketApproval.js, ui/components/RoundSettings/Granting/index.tsx
for https://github.com/cobudget/cobudget/issues/913
=> Rename boolean selects

ui/components/Bucket/EditCocreatorsModal.tsx, ui/components/Group/index.tsx, ui/components/SubMenu.tsx, ui/components/TodoList/index.js, ui/lang/index.ts, ui/server/graphql/resolvers/helpers.ts, ui/server/graphql/resolvers/mutations/bucket.ts, ui/server/graphql/resolvers/queries/group.ts, ui/server/graphql/resolvers/types/Round.ts, ui/server/graphql/schema/index.js, ui/tailwind.config.js
=> Redesign group page

ui/components/Bucket/EditBudgetModal.tsx
for https://github.com/cobudget/cobudget/issues/840#issuecomment-1359487774
=> fix: dependency variable

ui/components/Filterbar/index.js, ui/server/graphql/resolvers/queries/bucket.ts
for https://github.com/cobudget/cobudget/issues/391
=> Bucket search

ui/pages/[group]/[round]/index.tsx
for https://github.com/cobudget/cobudget/issues/925
=> fix: user balances

ui/components/Group/index.tsx, ui/pages/[group]/[round]/index.tsx
for https://github.com/cobudget/cobudget/issues/928
=> check null balances

ui/components/Bucket/Overview.tsx, ui/components/RoundSettings/Granting/SetCocreatorCanOpenFund.tsx, ui/components/RoundSettings/Granting/index.tsx, ui/pages/[group]/[round]/[bucket]/index.tsx, ui/server/graphql/resolvers/mutations/bucket.ts, ui/server/graphql/resolvers/mutations/round.ts, ui/server/graphql/schema/index.js, ui/server/prisma/migrations/20230119194927_corcreator_funding_permission/migration.sql, ui/server/prisma/schema.prisma
for https://github.com/cobudget/cobudget/issues/923
=> WIP: Bucket lifecycle and permissions

ui/components/Bucket/ContributeModal/FromBalance.tsx, ui/components/Bucket/Overview.tsx, ui/components/Bucket/Sidebar.tsx, ui/components/BucketCard.js, ui/components/Filterbar/StatusFilter.tsx, ui/graphql/client.ts, ui/pages/[group]/[round]/[bucket]/index.tsx, ui/server/graphql/resolvers/mutations/bucket.ts, ui/server/graphql/resolvers/types/Bucket.ts, ui/server/graphql/schema/index.js, ui/server/prisma/migrations/20230122210321_ready_for_funding_status/migration.sql, ui/server/prisma/schema.prisma
for Task 3
(https://github.com/cobudget/cobudget/issues/923#issuecomment-1397448619)
=> Bucket lifecycle changes

ui/components/TodoList/index.js
for https://github.com/cobudget/cobudget/issues/922
=> fix: check group members length

ui/components/Bucket/Infobox.jsx, ui/components/Bucket/Overview.tsx, ui/components/Bucket/Sidebar.tsx, ui/components/Bucket/index.tsx, ui/pages/[group]/[round]/[bucket]/index.tsx, ui/utils/getStatusColor.ts
for Task 4
(https://github.com/cobudget/cobudget/issues/923#issuecomment-1397448619)
=> Lifecycle infoboxes

ui/utils/parseMDSource.ts
for https://github.com/cobudget/cobudget/issues/944
=> handle null source

ui/tailwind.config.js
for https://github.com/cobudget/cobudget/issues/923#issuecomment-1426831712
=> fix: bucket status colors

ui/components/RequiredActions/FinishSignup.tsx
=> redirect on signup

ui/components/Bucket/EditBudgetModal.tsx, ui/components/Bucket/Title.js, ui/components/NewBucketModal.tsx, ui/constants/index.ts, ui/constants/length.ts, ui/server/graphql/resolvers/mutations/bucket.ts
for https://github.com/cobudget/cobudget/issues/951
Things to check:
1. Added a check in backend to make sure max goal is greater than min goal in editBucket mutation
2. Edit error message when max goal is not greater than min goal on frontend
**This PR also fixes https://github.com/cobudget/cobudget/issues/949**
=> Fixes(2 issues): max goal error & max bucket title length

ui/components/Group/index.tsx, ui/components/RoundSettings/Granting/index.tsx, ui/components/RoundSettings/Integrations/SetOpenCollective.tsx, ui/components/RoundSettings/Integrations/index.tsx, ui/components/RoundSettings/index.tsx, ui/constants/errors.ts, ui/constants/index.ts, ui/package.json, ui/pages/[group]/[round]/index.tsx, ui/server/graphql/resolvers/helpers/index.ts, ui/server/graphql/resolvers/helpers/opencollective.ts, ui/server/graphql/resolvers/mutations/round.ts, ui/server/graphql/resolvers/types/Round.ts, ui/server/graphql/schema/index.js, ui/server/prisma/migrations/20230225185603_opencollective_integration/migration.sql, ui/server/prisma/migrations/20230227194512_oc_project_id/migration.sql, ui/server/prisma/schema.prisma, ui/utils/graphqlClient.ts, ui/yarn.lock
=> Opencollective integration

ui/server/graphql/resolvers/queries/bucket.ts
for https://github.com/cobudget/cobudget/issues/974
=> fix: draft buckets

ui/components/RoundMembers/MembersTable.tsx, ui/components/RoundMembers/index.tsx, ui/constants/activity.ts, ui/constants/index.ts, ui/pages/_app.tsx, ui/utils/activity-log.ts, ui/utils/reportError.ts
More details added to error message
=> Detailed error

ui/components/RoundMembers/MembersTable.tsx
for https://github.com/cobudget/cobudget/issues/977 and https://github.com/cobudget/cobudget/issues/983
=> fix: check member email

ui/styles.css
=> Fix Remirror editor styles

ui/styles.css
Headings and blockquote style changes
=> editor heading and quote styles

ui/components/Bucket/Expenses/RoundExpensesFilter.tsx, ui/components/MultiSelect.tsx, ui/components/RoundExpenses.tsx, ui/constants/enums.ts, ui/server/graphql/resolvers/index.ts, ui/server/graphql/resolvers/queries/expense.ts, ui/server/graphql/resolvers/queries/index.ts, ui/server/graphql/schema/index.js
=> Expense Filters

ui/components/RoundExpenses.tsx, ui/server/graphql/resolvers/queries/expense.ts, ui/server/graphql/schema/index.js, ui/utils/usePaginatedQuery.ts
=> 1046 expense pagination

ui/components/RoundExpenses.tsx
for #1053 
Changed expense submission date formatting.
=> fix: date formatting

ui/components/Bucket/Expenses/ConversionElements.tsx, ui/components/Bucket/Expenses/ExpenseTable.tsx, ui/pages/[group]/[round]/[bucket]/index.tsx, ui/server/graphql/resolvers/helpers/getExchangeRate.ts, ui/server/graphql/resolvers/mutations/round.ts, ui/server/graphql/resolvers/queries/round.ts, ui/server/graphql/schema/index.js, ui/server/prisma/migrations/20230817041827_freeze_exchange_rate/migration.sql, ui/server/prisma/schema.prisma, ui/server/webhooks/ochandlers.ts
=> 1097 Freeze Exchange Rate

ui/components/RoundExpenses.tsx
fixes bucket link on round expenses page
=> Fix: bucket link

ui/components/RoundSettings/Integrations/index.tsx, ui/constants/errors.ts, ui/server/graphql/resolvers/mutations/round.ts, ui/server/graphql/schema/index.js, ui/server/utils/expenses.ts, ui/server/utils/getMap.ts
=> Optimize syncing OpenCollective expenses

ui/components/RoundSettings/Integrations/index.tsx, ui/constants/errors.ts, ui/server/graphql/resolvers/helpers/opencollective.ts, ui/server/graphql/resolvers/mutations/round.ts, ui/server/graphql/resolvers/queries/round.ts, ui/server/graphql/schema/index.js
=> Increase sync limit

ui/components/RoundMembers/MembersTable.tsx, ui/server/graphql/resolvers/mutations/round.ts, ui/server/graphql/schema/index.js, ui/server/services/EmailService/email.service.ts
=> Fix: Resend round invite

ui/pages/api/auth/magiclink/callback.ts, ui/pages/login.tsx, ui/server/passport/magicLink.ts, ui/server/prisma/migrations/20231203083014_magiclink_code/migration.sql, ui/server/prisma/schema.prisma
=> Expire Magic Links

ui/components/Elements/UpgradeGroupModal.tsx, ui/components/RoundSettings/SuperAdmin.tsx, ui/components/RoundSettings/index.tsx, ui/server/graphql/resolvers/helpers/isGroupSubscriptionActive.ts, ui/server/graphql/resolvers/mutations/round.ts, ui/server/graphql/resolvers/types/Round.ts, ui/server/graphql/schema/index.js
To fix https://github.com/cobudget/cobudget/issues/1190
=> [Feat] Change round size

ui/styles.css
As per Jonas request on Borderland Discord. Reduced first child top margin to 15 and increased last child bottom margin to 30. https://discord.com/channels/932714386286575736/1348961577256357958
=> Fix markdown margin
